\c dream_team_dev;

INSERT INTO cards
  (name, class, attack, defense, image_url)
VALUES
  ('Sammy', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Sally', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Billy', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Annie', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Timmy', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Lilly', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Willy', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Marty', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Sassy', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Lassie', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Lizzie', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Gilly', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Tommy', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Eddie', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Minnie', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Renny', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Jackie', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Poppy', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Vinnie', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Winnie', 'Pawn', 2, 2, '/images/pawn_card.png'),
  ('Aragorn', 'Knight', 5, 5, '/images/knight_card.png'),
  ('Ranger', 'Knight', 5, 5, '/images/knight_card.png'),
  ('Strider', 'Knight', 5, 5, '/images/knight_card.png'),
  ('Revere', 'Knight', 5, 5, '/images/knight_card.png'),
  ('Genghis', 'Knight', 5, 5, '/images/knight_card.png'),
  ('Godiva', 'Knight', 5, 5, '/images/knight_card.png'),
  ('Seabiscuit', 'Knight', 5, 5, '/images/knight_card.png'),
  ('Roosevelt', 'Knight', 5, 5, '/images/knight_card.png'),
  ('Khan', 'Knight', 5, 5, '/images/knight_card.png'),
  ('Crazy Horse', 'Knight', 5, 5, '/images/knight_card.png'),
  ('Obsidian', 'Castle', 4, 8, '/images/castle_card.png'),
  ('Ironsides', 'Castle', 4, 8, '/images/castle_card.png'),
  ('Onyx', 'Castle', 4, 8, '/images/castle_card.png'),
  ('Limestone', 'Castle', 4, 8, '/images/castle_card.png'),
  ('Shale', 'Castle', 4, 8, '/images/castle_card.png'),
  ('Archer', 'Castle', 4, 8, '/images/castle_card.png'),
  ('Tower', 'Castle', 4, 8, '/images/castle_card.png'),
  ('Bedrock', 'Castle', 4, 8, '/images/castle_card.png'),
  ('Francis', 'Bishop', 8, 4, '/images/bishop_card.png'),
  ('Benedict', 'Bishop', 8, 4, '/images/bishop_card.png'),
  ('Innocent', 'Bishop', 8, 4, '/images/bishop_card.png'),
  ('John Paul', 'Bishop', 8, 4, '/images/bishop_card.png'),
  ('Alexander', 'Bishop', 8, 4, '/images/bishop_card.png'),
  ('Pius', 'Bishop', 8, 4, '/images/bishop_card.png'),
  ('Gregory', 'Bishop', 8, 4, '/images/bishop_card.png'),
  ('Formosus', 'Bishop', 8, 4, '/images/bishop_card.png'),
  ('Victoria', 'Queen', 10, 10, '/images/queen_card.png'),
  ('Isabella', 'Queen', 10, 10, '/images/queen_card.png'),
  ('Henry', 'King', 2, 2, '/images/king_card.png'),
  ('Tut', 'King', 2, 2, '/images/king_card.png');

INSERT INTO counter_cards
  (name, description, usable_by)
VALUES
  ('Check',
  'Lower opponent card base DEF to 0',
  '{"Pawn", "Knight", "Castle", "Bishop", "King"}'),
  ('Blockade',
  'Lower opponent card base ATT to 0',
  '{"Pawn", "Knight", "Castle", "Bishop", "King"}'),
  ('Parry',
  'Add current card ATT value to DEF',
  '{"Pawn", "Knight", "Castle", "Bishop", "Queen", "King"}'),
  ('Riposte',
  'Add current card DEF value to ATT',
  '{"Pawn", "Knight", "Castle", "Bishop", "King"}'),
  ('Castling',
  '+ATT & +DEF values from another card currently in hand',
  '{"King"}'),
  ('Benevolence',
  '+6 Player HP',
  '{"King"}'),
  ('Regicide',
  '-10 Opponent HP vs Queen',
  '{"King"}'),
  ('Assassin',
  '+10 ATT vs Queen',
  '{"Pawn"}'),
  ('Kingslayer',
  'Double ATT/DEF vs King',
  '{"Pawn"}'),
  ('Hospitaller',
  '+2 Player HP',
  '{"Pawn"}'),
  ('Flank',
  'opponent card base ATT/DEF reduced to 0',
  '{"Knight"}'),
  ('Battle Royal',
  '+5 ATT/-5 DEF vs another Queen',
  '{"Queen"}');
